### ISSUE TITLE
Fix bug when getting topology

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kyco-core-napps#53]
```
2016-11-09 13:23:39,477 - WARNING [kyco.core.switch] (Thread-20) No speed port 65534, sw :db, feats 0
[2016-11-09 13:23:39,477] ERROR in app: Exception on /kytos/topology [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/kytos/napps/kytos/of.topology/main.py", line 58, in get_json_topology
    nodes.append(switch.as_dict())
  File "/usr/src/beraldo/ncc/github/kyco/kyco/core/switch.py", line 314, in as_dict
    'connection': "{}:{}".format(self.connection.address,
AttributeError: 'NoneType' object has no attribute 'address'
2016-11-09 13:23:39,477 - ERROR [kyco.controller] (Thread-20) Exception on /kytos/topology [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/kytos/napps/kytos/of.topology/main.py", line 58, in get_json_topology
    nodes.append(switch.as_dict())
  File "/usr/src/beraldo/ncc/github/kyco/kyco/core/switch.py", line 314, in as_dict
    'connection': "{}:{}".format(self.connection.address,
AttributeError: 'NoneType' object has no attribute 'address'
2016-11-09 13:23:39,479 - INFO [werkzeug] (Thread-20) 200.145.46.2```

**Comment by macartur** [comment]
This was fixed in kyco, when the pull request 133 was accept.
Pull request link: https://github.com/kytos/kyco/pull/133/files
